name: my_env
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=cpp
channels:
  - conda-forge
dependencies:
  - python=3.7.0
  - 
  - rdkit
  - pip
  - pip:
      - streamlit==0.71.0
      - pandas==1.1.3
      - numpy==1.19.2
      - Pillow==8.0.1
      - scikit-learn==0.23.2
      - pickle5
      - click==8
